config/routes.rb
Rails.application.routes.draw do
  resources :products
  mount RailsAdmin::Engine => '/reyiz', as: 'rails_admin'
  root to: "home#index"
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  resources :movies
  resources :casts
  resources :categories
  resources :comments
  resources :companies
  resources :contents
  resources :medias
  resources :votes

end

app/models/actor_movie.rb
class ActorMovie < ActiveRecord::Base
  belongs_to :movie
  belongs_to :cast
end

app/models/cast.rb
class Cast < ActiveRecord::Base
  has_many :director_movies
  has_many :actor_movies
  has_many :movie_writers
  has_many :cast_medias
  has_many :movies_directed, through: :director_movies, source: :movie #Movie tablosunda arama yapar
  has_many :movies_acted, through: :actor_movies, source: :movie #Source tablosunda arama yapar
  has_many :movies_writed, through: :movie_writers, source: :movie #
  has_many :medias, through: :cast_medias
end

app/models/cast_media.rb
class CastMedia < ActiveRecord::Base
  belongs_to :cast
  belongs_to :media
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/category_movie.rb
class CategoryMovie < ActiveRecord::Base
  belongs_to :category
  belongs_to :movie
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :movie
  belongs_to :user
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :company_movies
  has_many :movies, through: :company_movies
end

app/models/company_movie.rb
class CompanyMovie < ActiveRecord::Base
  belongs_to :company
  belongs_to :movie
end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :movie
end

app/models/director_movie.rb
class DirectorMovie < ActiveRecord::Base
  belongs_to :movie
  belongs_to :cast
end

app/models/media.rb
class Media < ActiveRecord::Base
  has_many :media_movies
  has_many :cast_medias
  has_many :movies, through: :media_movies
  has_many :casts, through: :cast_medias
end

app/models/media_movie.rb
class MediaMovie < ActiveRecord::Base
  belongs_to :media
  belongs_to :movie
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :director_movies
  has_many :actor_movies
  has_many :category_movies
  has_many :movie_writers
  has_many :media_movies
  has_many :company_movies
  has_many :contents #Type a gore View de gorunum degisecekse has_many olacaktir misal SSS ise asagi detail ise yukari gibi
  has_many :comments #Movie_id ler Comments tablosunda tutular duz iliski ile
  has_many :medias, through: :media_movies
  has_many :directors, through: :director_movies, source: :cast
  has_many :actors, through: :actor_movies, source: :cast
  has_many :categories, through: :category_movies
  has_many :writers, through: :movie_writers, source: :cast
  has_many :companies, through: :company_movies
end

app/models/movie_writer.rb
class MovieWriter < ActiveRecord::Base
  belongs_to :cast
  belongs_to :movie
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments #user_id ler comment tablosunda tutulur
end

app/models/vote.rb
class Vote < ActiveRecord::Base
end

app/controllers/casts_controller.rb
class CastsController < ApplicationController
  before_action :set_cast, only: [:show,:destroy,:update,:edit]
  def index
    @casts = Cast.all
  end
  def new
    @cast = Cast.new
  end
  def show
  @cast = Cast.find(params[:id])
  end
  def create
    @cast = Cast.create(cast_params)
    redirect_to @cast
  end
  def destroy
    @cast.destroy
    respond_to do |format|
      format.html { redirect_to @cast, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
  def set_cast
    @cast = Cast.find(params[:id])
  end
  def cast_params
    params.require(:cast).permit(:first_name, :last_name, :age, :bio, :photo, :detail)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show,:edit,:update,:destroy]
  def index
    @comments = Comment.all
  end
  def show

  end
  def new
    @comment = Comment.new()
    @movies = Movie.all
    @movies_array = @movies.map{ |movie| [" #{movie.id} .) #{movie.title} ",movie.id] }
    @users = User.all
    @users_array = @users.map{ |user| [" #{user.id} .) #{user.fist_name} ",user.id] }
  end
  def create
    @comment = Comment.create(comment_params)
    redirect_to @comment
  end
  def edit
    @movies = Movie.all
    @users = User.all
    @movies_array = @movies.map{ |movie| [" #{movie.id} .) #{movie.title} ",movie.id] }
    @users_array = @users.map{ |user| [" #{user.id} .) #{user.fist_name} ",user.id] }
  end
  def update
    if @comment.update(comment_params)
      redirect_to @comment, notice: 'Comment was successfully updated.'
    else
      render :edit
    end
    end
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @comment, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
  def set_comment
    @comment = Comment.find(params[:id])
  end
  def comment_params
    params.require(:comment).permit(:user_id, :movie_id, :content, :is_active)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show,:update,:edit,:destroy]
  def index
    @companies = Company.all
  end
  def show
    @movies = @company.movies
    if @movies.kind_of?(Array)
      @movies_array = @movies.map{ |movie| [" #{movie.id} .) #{movie.title} ",movie.id] }
    else
      @movies_array = @movies
    end
  end

  def new
    @movies = Movie.all
    @movies_array = @movies.map{ |movie| [" #{movie.id} .) #{movie.title} ",movie.id] }
    @company = Company.new()
  end
  def create
    @company = Company.create(company_params)
    CompanyMovie.create(movie_id: params[:movie_id], company_id: @company.id)
    redirect_to @company
  end
  def edit
    @movies = Movie.all
    @company_movies = @company.movies
  end
  def update
    @company.update(company_params)
    redirect_to @company
  end
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to @company, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
  def set_company
    @company = Company.find(params[:id])
  end
  def company_params
    params.require(:company).permit(:name, :detail, :movie_id)
  end
end

app/controllers/medias_controller.rb
class MediasController < ApplicationController
  before_action :set_media, only: [:show,:edit,:update,:destroy]
  def index

  end
  def show

  end
  def new

  end
  def create

  end
  private
  def set_media
    @media = Media.find(params[:id])
  end
  def media_params
    params.require(:media).permit()
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show,:edit,:update,:destroy]
  def index
    @movies = Movie.all
  end
  def new
    @movie = Movie.new
    @casts = Cast.all
    @categories = Category.all
  end
  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to @movie
    else
      render 'new'
    end
  end
  def show
    @movie = Movie.find(params[:id])
  end
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to @movie, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit
    @casts = Cast.all
    @categories = Category.all
  end

  def update
    if @movie.update(movie_params)
      redirect_to @movie
    else
      render 'edit'
    end
  end

  private
  def set_movie
    @movie = Movie.find(params[:id])
  end
  def movie_params
    params.require(:movie).permit(:title, :description,:keywords, :storyline, :techspecs, :detail, director_ids: [], writer_ids: [], actor_ids: [], category_ids: [] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
    <% if @company.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@company.errors.count, "error") %> prohibited this topic from being saved:</h2>

          <ul>
            <% @company.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :detail %><br>
      <%= f.text_field :detail %>
    </div>
    <%= select(:movie_id, options_for_select(movies_array.map{ |movie| [" #{movie.id} .) #{movie.title} ",movie.id] }))%>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/companies/_showcompany.html.erb
<h1>    Company id with <%= company.id %></h1>
Company name : <%= company.name %>
<p>Company details : <%= company.detail %></p>
<% movies_array.try(:each) do |movie| %>
    <%= "#{movie.id} .) #{movie.title}" %>
<% end %>
<%= link_to 'destroy', company_path(company), method: :delete %>

app/views/companies/edit.html.erb
<h1>    Company       </h1>
<%= render 'showcompany', movies_array: @company_movies, company: @company %>
<%= form_for(@company) do |f| %>
    <% if @company.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@company.errors.count, "error") %> prohibited this topic from being saved:</h2>

          <ul>
            <% @company.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :detail %><br>
      <%= f.text_field :detail %>
    </div>
    <%     movies_array.each do |movie| %>
        <input type="checkbox" name="movie_ids[]" value="<%= movie.id %>"/>
        <%= f.label movie.title     %>
    <% end %>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/companies/index.html.erb
<h1>    Companies Lists     </h1>
<% @companies.each do |company| %>

    <% movies = company.movies %>
   <% if movies.kind_of?(Array) %>
    <% movies_array = movies.map{ |movie| [" #{movie.id} .) #{movie.title} ",movie.id] } %>
    <%else %>
    <% movies_array = movies %>
    <%end %>

    <%= render 'showcompany', company: company, movies_array: movies_array %>
<% end %>

app/views/companies/new.html.erb
<h1>    New Company      </h1>
<%= render 'form', movies_array: @movies_array %>

app/views/companies/show.html.erb
<%= render 'showcompany', company: @company, movies_array: @movies_array %>