config/routes.rb
Rails.application.routes.draw do
  resources :products
  mount RailsAdmin::Engine => '/reyiz', as: 'rails_admin'
  root to: "home#index"
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  resources :movies
  resources :casts
  resources :categories
  resources :comments
  resources :companies
  resources :contents
  resources :medias
  resources :votes

end

app/models/actor_movie.rb
class ActorMovie < ActiveRecord::Base
  belongs_to :movie
  belongs_to :cast
end

app/models/cast.rb
class Cast < ActiveRecord::Base
  has_many :director_movies
  has_many :actor_movies
  has_many :movie_writers
  has_many :cast_medias
  has_many :movies_directed, through: :director_movies, source: :movie #Movie tablosunda arama yapar
  has_many :movies_acted, through: :actor_movies, source: :movie #Source tablosunda arama yapar
  has_many :movies_writed, through: :movie_writers, source: :movie #
  has_many :medias, through: :cast_medias
end

app/models/cast_media.rb
class CastMedia < ActiveRecord::Base
  belongs_to :cast
  belongs_to :media
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/category_movie.rb
class CategoryMovie < ActiveRecord::Base
  belongs_to :category
  belongs_to :movie
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :movie
  belongs_to :user
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :company_movies
  has_many :movies, through: :company_movies
end

app/models/company_movie.rb
class CompanyMovie < ActiveRecord::Base
  belongs_to :company
  belongs_to :movie
end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :movie
end

app/models/director_movie.rb
class DirectorMovie < ActiveRecord::Base
  belongs_to :movie
  belongs_to :cast
end

app/models/media.rb
class Media < ActiveRecord::Base
  has_many :media_movies
  has_many :cast_medias
  has_many :movies, through: :media_movies
  has_many :casts, through: :cast_medias
end

app/models/media_movie.rb
class MediaMovie < ActiveRecord::Base
  belongs_to :media
  belongs_to :movie
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :director_movies
  has_many :actor_movies
  has_many :category_movies
  has_many :movie_writers
  has_many :media_movies
  has_many :company_movies
  has_many :contents #Type a gore View de gorunum degisecekse has_many olacaktir misal SSS ise asagi detail ise yukari gibi
  has_many :comments #Movie_id ler Comments tablosunda tutular duz iliski ile
  has_many :medias, through: :media_movies
  has_many :directors, through: :director_movies, source: :cast
  has_many :actors, through: :actor_movies, source: :cast
  has_many :categories, through: :category_movies
  has_many :writers, through: :movie_writers, source: :cast
  has_many :companies, through: :company_movies
end

app/models/movie_writer.rb
class MovieWriter < ActiveRecord::Base
  belongs_to :cast
  belongs_to :movie
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments #user_id ler comment tablosunda tutulur
end

app/models/vote.rb
class Vote < ActiveRecord::Base
end

app/controllers/casts_controller.rb
class CastsController < ApplicationController
  before_action :set_cast, only: [:show,:destroy,:update,:edit]
  def index
    @casts = Cast.all
  end
  def new
    @cast = Cast.new
  end
  def show
  @cast = Cast.find(params[:id])
  end
  def create
    @cast = Cast.create(cast_params)
    redirect_to @cast
  end
  def destroy
    @cast.destroy
    respond_to do |format|
      format.html { redirect_to @cast, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
  def set_cast
    @cast = Cast.find(params[:id])
  end
  def cast_params
    params.require(:cast).permit(:first_name, :last_name, :age, :bio, :photo, :detail)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show,:edit,:update,:destroy]
  def index
    @comments = Comment.all
  end
  def show

  end
  def new
    @comment = Comment.new()
    @movies = Movie.all
    @movies_array = @movies.map{ |movie| [" #{movie.id} .) #{movie.title} ",movie.id] }
    @users = User.all
    @users_array = @users.map{ |user| [" #{user.id} .) #{user.fist_name} ",user.id] }
  end
  def create
    @comment = Comment.create(comment_params)
    redirect_to @comment
  end
  def edit
    @movies = Movie.all
    @users = User.all
    @movies_array = @movies.map{ |movie| [" #{movie.id} .) #{movie.title} ",movie.id] }
    @users_array = @users.map{ |user| [" #{user.id} .) #{user.fist_name} ",user.id] }
  end
  def update
    if @comment.update(comment_params)
      redirect_to @comment, notice: 'Comment was successfully updated.'
    else
      render :edit
    end
    end
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @comment, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
  def set_comment
    @comment = Comment.find(params[:id])
  end
  def comment_params
    params.require(:comment).permit(:user_id, :movie_id, :content, :is_active)
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show,:edit,:update,:destroy]
  def index
    @contents = Content.all
  end
  def show

  end
  def new
    @content = Content.new()
  end
  def create
    @content = Content.create(content_params)
    redirect_to @content
  end
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to @content, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
  def set_content
    @content = Content.find(params[:id])
  end
  def content_params
    params.require(:content).permit(:title, :description, :content, :kind)
  end
end

app/controllers/medias_controller.rb
class MediasController < ApplicationController
  before_action :set_media, only: [:show,:edit,:update,:destroy]
  def index

  end
  def show

  end
  def new

  end
  def create

  end
  private
  def set_media
    @media = Media.find(params[:id])
  end
  def media_params
    params.require(:media).permit()
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show,:edit,:update,:destroy]
  def index
    @movies = Movie.all
  end
  def new
    @movie = Movie.new
    @casts = Cast.all
    @categories = Category.all
  end
  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to @movie
    else
      render 'new'
    end
  end
  def show
    @movie = Movie.find(params[:id])
  end
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to @movie, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit
    @casts = Cast.all
    @categories = Category.all
  end

  def update
    if @movie.update(movie_params)
      redirect_to @movie
    else
      render 'edit'
    end
  end

  private
  def set_movie
    @movie = Movie.find(params[:id])
  end
  def movie_params
    params.require(:movie).permit(:title, :description,:keywords, :storyline, :techspecs, :detail, director_ids: [], writer_ids: [], actor_ids: [], category_ids: [] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/casts/_form.html.erb
<%= form_for(@cast) do |f| %>
    <% if @cast.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this topic from being saved:</h2>

          <ul>
            <% @cast.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :age %><br>
      <%= f.text_field :age %>
    </div>
    <div class="field">
      <%= f.label :bio %><br>
      <%= f.text_field :bio %>
    </div>
    <!-- Buraya PHOTO UPLOAD BOLUMU GELECEK -->
    <div class="field">
      <%= f.label :detail %><br>
      <%= f.text_field :detail %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/casts/_showcast.html.erb
<h1>   Cast id with <%= cast.id %></h1>
Cast first_name :  <%= cast.first_name %><br>
Cast last_name : <%= cast.last_name %><br>
Age : <%= cast.age %><br>
<p>Biography : <%= cast.bio %></p>
<p>Details : <%= cast.detail %></p>
<%= link_to 'destroy', cast_path(cast), method: :delete %>

app/views/casts/index.html.erb
<h1>    Cast Lists      </h1>
<% @casts.each do |cast| %>
<%= render 'showcast', cast: cast %>
<% end %>

app/views/casts/new.html.erb
<h1>    New Cast      </h1>
<%= render 'form' %>

app/views/casts/show.html.erb
<%= render 'showcast', cast: @cast %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
    <% if @comment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this topic from being saved:</h2>

          <ul>
            <% @comment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :content %><br>
      <%= f.text_field :content %>
    </div>
    <%= f.select(:user_id, options_for_select(@users_array)) %>
    <%= f.select(:movie_id,options_for_select(@movies_array)) %>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/comments/_showcomment.html.erb
<h1>    Comment id with <%= comment.id %>  </h1>
Comment's movie : <%= comment.movie.title %><br>
Comments's user : <%= "#{comment.user.fist_name}  #{comment.user.last_name}" %>
<p>Comment content : <%= comment.content %></p>
<%= link_to 'destroy', comment_path(comment), method: :delete %>

app/views/comments/edit.html.erb
<%= render 'showcomment', comment: @comment %>
<%= render 'form', comment: @comment%>

app/views/comments/index.html.erb
<h1>    Comments Lists      </h1>
<% @comments.each do |comment| %>
    <%= render 'showcomment', comment: comment %>
<% end %>

app/views/comments/new.html.erb
<h1>    New Comment     </h1>
<%= render 'form' %>

app/views/comments/show.html.erb
<%= render 'showcomment', comment: @comment %>

app/views/contents/_form.html.erb
<%= form_for(@content) do |f| %>
    <% if @content.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@content.errors.count, "error") %> prohibited this topic from being saved:</h2>

          <ul>
            <% @content.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_field :description %>
    </div>
    <div class="field">
      <%= f.label :content %><br>
      <%= f.text_field :content %>
    </div>
    <div class="field">
      <%= f.label :kind %><br>
      <%= f.text_field :kind %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/contents/_showcontent.html.erb
<h1>    Content id with <%= content.id %></h1>
<h3><%= content.kind %></h3>
Content title : <%= content.title %>
<p> Content description : <%= content.description %> </p>
<p> Content : <%= content.content %> </p>
<%= link_to 'destroy', content_path(content), method: :delete %>

app/views/contents/index.html.erb
<h1>    Contents Lists      </h1>
<% @contents.each do |content| %>
    <%= render 'showcontent', content: content %>
<% end %>

app/views/contents/new.html.erb
<h1>    New Content     </h1>
<%= render 'form' %>

app/views/contents/show.html.erb
<%= render 'showcontent',content: @content %>